name: CI/CD Pipeline for AI Code Review App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write  # For future PR comments if you add Ollama review

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8  # For PEP8 linting

      - name: Lint with flake8 (PEP8 checks)
        run: |
          # Report issues but don't fail on warnings; adjust as needed
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

      - name: Run Streamlit smoke tests
        uses: streamlit/streamlit-app-action@v0.0.3
        with:
          app-path: app.py  # Your main file
          # Optional: enable Ruff linting if you add it later
          # ruff: true

  # Optional: Deploy job (runs only after CI passes on main pushes)
  deploy:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: lint-and-test  # Wait for CI to succeed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Confirm deployment ready
        run: echo "Build successful. Streamlit Community Cloud will auto-deploy via GitHub integration."
